title: Itsnotstatic
author:
  name: Martin Kerger
  email: 'joe@test.com'
blog:
  route: ''
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'

taxonomies: [category,tag,month, author]
redirects:
    /changelog: /blog/the-urban-jungle
routes:
    /something/else: /blog/focus-and-blur
    /another/one/(.*): /blog/$1

